version: '3.7'

services:
  client:
    build: 
      context: .
      target: development
    env_file: ./.env
    ports:
      - $HOST_PORT:$CONTAINER_PORT
    volumes:
      - ./:/app
    command: sh -c "npm run serve"
